# Set version automatically from the latest tag in git
# Drop leading 'v', e.g. from v0.8.13
{% set tagged_version = GIT_DESCRIBE_TAG|replace("v","") %}

# If we aren't sitting at a tag directly, but some N commits after,
# append ".postN" to the version
{% if GIT_DESCRIBE_NUMBER|int != 0 %}
  {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
{% endif %}

package:
  name: dvid
  version: {{tagged_version}}

about:
  home: http://github.com/janelia-flyem/dvid
  license: BSD
  summary: Distributed, Versioned, Image-oriented Dataservice

build:
  number: 0

  # The lz4-c package declares 'run_exports' requirements,
  # effectively adding lz4-c to dvid's 'run' requirements
  # (even though it isn't listed in the 'run' section below).
  # But dvid *statically* links lz4-c, so we don't need the
  # lz4-c dylib at runtime.
  # This 'ignore' setting overrides lz4-c's 'run_exports' setting.
  ignore_run_exports:
    - lz4-c

  # Permit these variables in the user's environment to be inherited by build.sh
  script_env:
    - DVID_BACKENDS
    - DVID_LOW_MEMORY
    - GOMAXPROCS
    - GOTRACEBACK
    - GODEBUG

requirements:
  # The 'build' environment is for the tools that
  # are used to build dvid, but are not linked against
  # or incorporated into the executable in any way.
  build:
    
    - go=1.12 # From flyem-forge, not conda-forge!

    # Anaconda's gcc build -- on Linux only for now
    # (getting their clang binary to work on recent versions of MacOS is
    # tricky for some reason, related to SDK versions, etc.)
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

    - pkg-config

  # The 'host' environment is for libraries that
  # will be included/linked into dvid.
  #
  # Note:
  #  If you add/change anything in this 'host' list (or the 'build' list above),
  #  please also edit scripts/install-developer-dependencies.sh
  host:
    - snappy
    - basholeveldb
    - lz4-c {{ lz4_c }}*
    - librdkafka {{ librdkafka }}*

  # The 'run' requirements specify which libraries
  # are required by dvid at run-time.
  run:
    - basholeveldb
    - librdkafka {{ librdkafka }}*
    - dvid-web-console

source:
  - git_url: ../../
    git_tag: HEAD
    folder:  src/github.com/janelia-flyem/dvid

  # Janelia go packages
  - git_url: https://github.com/janelia-flyem/go
    git_tag: master
    folder: src/github.com/janelia-flyem/go
    # Includes many:
    #   basholeveldb cron freetype-go go-humanize go-uuid
    #   go.image gocheck goexif goji golz4-updated 
    #   levigo lru lumberjack msgp murmur3 nrsc profiler resize semver
    #   toml uuid

  # gojsonschema
  - git_url: https://github.com/janelia-flyem/gojsonschema
    git_tag: master
    folder: src/github.com/janelia-flyem/gojsonschema

  # goji
  - git_url: https://github.com/zenazn/goji
    git_tag: master
    folder:  src/github.com/zenazn/goji

  # go-jwt
    git_url: https://github.com/dgrijalva/jwt-go
    git_tag: master
    folder: src/github.com/dgrijalva/jwt-go

  # msgp
  #  - git_url: https://github.com/tinylib/msgp
  #    git_tag: master
  #    folder:  src/github.com/tinylib/msgp

  # net
  - git_url: https://go.googlesource.com/net
    git_tag: master
    folder:  src/golang.org/x/net
    # Includes:
    #        src/golang.org/x/net/context

  # lumberjack
  - git_url: https://gopkg.in/natefinch/lumberjack.v2
    git_tag: v2.0
    folder:  src/gopkg.in/natefinch/lumberjack.v2

  # snappy
  - git_url: https://github.com/golang/snappy
    git_tag: master
    folder:  src/github.com/golang/snappy

  # groupcache
  - git_url: https://github.com/golang/groupcache
    git_tag: master
    folder:  src/github.com/golang/groupcache

  # oauth2
  - git_url: https://go.googlesource.com/oauth2
    git_tag: master
    folder:  src/golang.org/x/oauth2

  # gcloud
  - git_url: https://code.googlesource.com/gocloud
    git_tag: master
    folder:  src/cloud.google.com/go
    # Includes:
    #        cloud.google.com/go/compute/metadata
    #        cloud.google.com/go/bigtable
    #        cloud.google.com/go/storage

  - git_url: https://code.googlesource.com/google-api-go-client
    git_tag: master
    folder:  src/google.golang.org/api
    # Includes:
    #        src/google.golang.org/api/option

  # grpc (not gorpc)
  - git_url: https://github.com/grpc/grpc-go
    git_tag: master
    folder:  src/google.golang.org/grpc

  # gorpc (not grpc)
  - git_url: https://github.com/valyala/gorpc
    git_tag: master
    folder:  src/github.com/valyala/gorpc

  # protobuf (golang)
  - git_url: https://github.com/golang/protobuf
    git_tag: master
    folder:  src/github.com/golang/protobuf
    # Includes:
    #        src/github.com/golang/protobuf/proto
    #        src/github.com/golang/protobuf/protoc-gen-go

  # protobuf (gogo)
  - git_url: https://github.com/gogo/protobuf
    git_tag: master
    folder:  src/github.com/gogo/protobuf
    # Includes:
    #        src/github.com/gogo/protobuf/proto
    #        src/github.com/gogo/protobuf/gogoproto
    #        src/github.com/gogo/protobuf/protoc-gen-gogoslick

  # gofuse
  - git_url: https://github.com/bazil/fuse
    git_tag: master
    folder:  src/bazil.org/fuse

  # gobolt
  - git_url: https://github.com/boltdb/bolt
    git_tag: master
    folder:  src/github.com/boltdb/bolt

  # kafka
  #  NOTE: Using v0.11.6 for now, until we obtain a build of librdkafka 1.0
  #        If you change this tag, please also change it in scripts/get-go-dependencies.sh
  - git_url: https://github.com/confluentinc/confluent-kafka-go
    git_tag: v0.11.6
    folder:  src/github.com/confluentinc/confluent-kafka-go
    
  # freecache
  - git_url: https://github.com/coocood/freecache
    git_tag: master
    folder:  src/github.com/coocood/freecache

  # Openstack Swift
  - git_url: https://github.com/ncw/swift
    git_tag: master
    folder:  src/github.com/ncw/swift

  # badger
  - git_url: https://github.com/dgraph-io/badger
    git_tag: v2.0.0 # Don't change this without also changing it in get-go-dependencies.sh!!!
    folder:  src/github.com/dgraph-io/badger

  # ristretto
  - git_url: https://github.com/dgraph-io/ristretto
    git_tag: v0.0.1 # Don't change this without also changing it in get-go-dependencies.sh!!!
    folder:  src/github.com/dgraph-io/ristretto

  # protolog
  - git_url: https://github.com/janelia-flyem/protolog
    git_tag: master
    folder:  src/github.com/janelia-flyem/protolog