# Set version automatically from the latest tag in git
# Drop leading 'v', e.g. from v0.8.13
#
# Note:
#   If conda-build fails due to the following error:
#
#     "'GIT_DESCRIBE_TAG' is undefined",
#
#   ...then it's likely that one of the git repos below could not be cloned.
#   Inspect the conda-build output for the specific error.
{% set tagged_version = GIT_DESCRIBE_TAG|replace("v","") %}

# If we aren't sitting at a tag directly, but some N commits after,
# append ".postN" to the version
{% if GIT_DESCRIBE_NUMBER|int != 0 %}
  {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
{% endif %}

package:
  name: dvid
  version: {{tagged_version}}

about:
  home: http://github.com/janelia-flyem/dvid
  license: BSD
  summary: Distributed, Versioned, Image-oriented Dataservice

build:
  number: 0

  # Permit these variables in the user's environment to be inherited by build.sh
  script_env:
    - DVID_BACKENDS
    - DVID_LOW_MEMORY
    - DVID_CONDA_SKIP_TESTS
    - GOMAXPROCS
    - GOTRACEBACK
    - GODEBUG

requirements:
  # The 'build' environment is for the tools that
  # are used to build dvid, but are not linked against
  # or incorporated into the executable in any way.
  build:
    - make
    - python

    # Note: Make sure this matches go.mod and GO_VERSION in scripts/install-conda-dev-toolchain.sh
    - go-cgo=1.25

    - {{ compiler('c') }}

  # The 'run' requirements specify which libraries
  # are required by dvid at run-time.
  run:
    - dvid-web-console

source:
  - git_url: ../../
    git_tag: HEAD
    folder:  src/github.com/janelia-flyem/dvid
