# Set version automatically from the latest tag in git
# Drop leading 'v', e.g. from v0.8.13
#
# Note:
#   If conda-build fails due to the following error:
#
#     "'GIT_DESCRIBE_TAG' is undefined",
#
#   ...then it's likely that one of the git repos below could not be cloned.
#   Inspect the conda-build output for the specific error.
{% set tagged_version = GIT_DESCRIBE_TAG|replace("v","") %}

# If we aren't sitting at a tag directly, but some N commits after,
# append ".postN" to the version
{% if GIT_DESCRIBE_NUMBER|int != 0 %}
  {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
{% endif %}

package:
  name: dvid
  version: {{tagged_version}}

about:
  home: http://github.com/janelia-flyem/dvid
  license: BSD
  summary: Distributed, Versioned, Image-oriented Dataservice

build:
  number: 0

  # The lz4-c package declares 'run_exports' requirements,
  # effectively adding lz4-c to dvid's 'run' requirements
  # (even though it isn't listed in the 'run' section below).
  # But dvid *statically* links lz4-c, so we don't need the
  # lz4-c dylib at runtime.
  # This 'ignore' setting overrides lz4-c's 'run_exports' setting.
  ignore_run_exports:
    - lz4-c

  # Permit these variables in the user's environment to be inherited by build.sh
  script_env:
    - DVID_BACKENDS
    - DVID_LOW_MEMORY
    - DVID_CONDA_SKIP_TESTS
    - GOMAXPROCS
    - GOTRACEBACK
    - GODEBUG

requirements:
  # The 'build' environment is for the tools that
  # are used to build dvid, but are not linked against
  # or incorporated into the executable in any way.
  build:
    - make

    # Note: Make sure this matches GO_VERSION in scripts/install-developer-dependencies.sh
    - go-cgo=1.21

    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

    - pkg-config

  # The 'host' environment is for libraries that
  # will be included/linked into dvid.
  #
  # Note:
  #  If you add/change anything in this 'host' list (or the 'build' list above),
  #  please also edit scripts/install-developer-dependencies.sh
  host:
    - snappy
    - basholeveldb
    - lz4-c {{ lz4_c }}*

  # The 'run' requirements specify which libraries
  # are required by dvid at run-time.
  run:
    - basholeveldb
    - dvid-web-console

source:
  - git_url: ../../
    git_tag: HEAD
    folder:  src/github.com/janelia-flyem/dvid
