/*
	This file supports keyspaces for voxel-related data types.  See doc for KeyType.
*/

package voxels

import (
	"encoding/binary"
	"fmt"

	"github.com/janelia-flyem/dvid/dvid"
	"github.com/janelia-flyem/dvid/storage"
)

// KeyType is the first byte of a type-specific index, allowing partitioning of the
// type-specific key space.
//
// Voxel block and label indexing is handled through a variety of key spaces that optimize
// throughput for access patterns required by our API.  It is essential that any
// data type has a consistent key space, including keys that might be generated by
// any derived data type that uses embedding.  For example, labels64 embeds the voxels
// data type and has a number of different index types to accelerate various lookups.
// These key spaces must not collide, so a common first byte is used where we explicitly
// demarcate the key spaces.
type KeyType byte

// For dcumentation purposes, consider the following key components:
//   a: original label
//   b: mapped label
//   s: spatial index (coordinate of a block)
//   v: # of voxels for a label
const (
	// KeyUnknown should never be used and is a check for corrupt or incorrectly set keys
	KeyUnknown KeyType = iota

	// KeyVoxelBlock have keys of form 's'
	KeyVoxelBlock

	// KeyForwardMap have keys of form 'a+b'
	// For superpixel->body maps, this key would be superpixel+body.
	KeyForwardMap

	// KeyInverseMap have keys of form 'b+a'
	KeyInverseMap

	// KeySpatialMap have keys of form 's+a+b'
	// They are useful for composing label maps for a spatial index.
	KeySpatialMap

	// KeyLabelSpatialMap have keys of form 'b+s' and have a sparse volume
	// encoding for its value. They are useful for returning all blocks
	// intersected by a label.
	KeyLabelSpatialMap

	// KeyLabelSizes have keys of form 'v+b'.
	// They allow rapid size range queries.
	KeyLabelSizes

	// KeyLabelSurface have keys of form 'b' and have the label's sparse volume
	// for its value.
	KeyLabelSurface
)

func (t KeyType) String() string {
	switch t {
	case KeyUnknown:
		return "Unknown Key Type"
	case KeyVoxelBlock:
		return "Voxel block"
	case KeyForwardMap:
		return "Forward Label Map"
	case KeyInverseMap:
		return "Inverse Label Map"
	case KeySpatialMap:
		return "Spatial Index to Labels Map"
	case KeyLabelSpatialMap:
		return "Forward Label to Spatial Index Map"
	case KeyLabelSizes:
		return "Forward Label sorted by volume"
	case KeyLabelSurface:
		return "Forward Label Surface"
	default:
		return "Unknown Key Type"
	}
}

// BlockKeyToIndexZYX parses a voxel block key and returns its IndexZYX.
func BlockKeyToIndexZYX(k []byte) (dvid.IndexZYX, error) {
	var zyx dvid.IndexZYX
	ctx := &storage.DataContext{}
	indexBytes, err := ctx.IndexFromKey(k)
	if err != nil {
		return zyx, fmt.Errorf("Can't get index from presumed voxels block key (%v): %s",
			k, err.Error())
	}
	if indexBytes[0] != byte(KeyVoxelBlock) {
		return zyx, fmt.Errorf("Instead of expected KeyVoxelBlock (%d) got %d",
			KeyVoxelBlock, indexBytes[0])
	}
	if err := zyx.IndexFromBytes(indexBytes[1:]); err != nil {
		return zyx, fmt.Errorf("Cannot recover ZYX index from key %v: %s\n", k, err.Error())
	}
	return zyx, nil
}

// NewVoxelBlockIndex returns an index for a voxel block.
// Index = s
func NewVoxelBlockIndex(blockIndex dvid.Index) []byte {
	indexBytes := blockIndex.Bytes()
	sz := len(indexBytes)
	index := make([]byte, 1+sz)
	index[0] = byte(KeyVoxelBlock)
	copy(index[1:1+sz], indexBytes)
	return dvid.IndexBytes(index)
}

// NewForwardMapIndex returns an index for mapping a label into another label.
// Index = a+b
// For dcumentation purposes, consider the following key components:
//   a: original label
//   b: mapped label
//   s: spatial index (coordinate of a block)
//   v: # of voxels for a label
func NewForwardMapIndex(label []byte, mapping uint64) []byte {
	index := make([]byte, 17)
	index[0] = byte(KeyForwardMap)
	copy(index[1:9], label)
	binary.BigEndian.PutUint64(index[9:17], mapping)
	return dvid.IndexBytes(index)
}

// NewInverseMapIndex returns an index for mapping a label into another label.
// Index = b+a
func NewInverseMapIndex(label []byte, mapping uint64) []byte {
	index := make([]byte, 17)
	index[0] = byte(KeyInverseMap)
	binary.BigEndian.PutUint64(index[1:9], mapping)
	copy(index[9:17], label)
	return dvid.IndexBytes(index)
}

// NewSpatialMapIndex returns an index optimizing access to label maps for a given
// spatial index. Index = s+a+b
func NewSpatialMapIndex(blockIndex dvid.Index, label []byte, mapping uint64) []byte {
	indexBytes := blockIndex.Bytes()
	sz := len(indexBytes)
	index := make([]byte, 1+sz+8+8) // s + a + b
	index[0] = byte(KeySpatialMap)
	i := 1 + sz
	copy(index[1:i], indexBytes)
	if label != nil {
		copy(index[i:i+8], label)
	}
	binary.BigEndian.PutUint64(index[i+8:i+16], mapping)
	return dvid.IndexBytes(index)
}

// NewLabelSpatialMapIndex returns an identifier for storing a "label + spatial index", where
// the spatial index references a block that contains a voxel with the given label.
func NewLabelSpatialMapIndex(label uint64, blockIndex dvid.Index) []byte {
	indexBytes := blockIndex.Bytes()
	sz := len(indexBytes)
	index := make([]byte, 1+8+sz)
	index[0] = byte(KeyLabelSpatialMap)
	binary.BigEndian.PutUint64(index[1:9], label)
	copy(index[9:9+sz], indexBytes)
	return dvid.IndexBytes(index)
}

// NewLabelSizesIndex returns an identifier for storing a "size + mapped label".
func NewLabelSizesIndex(size, label uint64) []byte {
	index := make([]byte, 17)
	index[0] = byte(KeyLabelSizes)
	binary.BigEndian.PutUint64(index[1:9], size)
	binary.BigEndian.PutUint64(index[9:17], label)
	return dvid.IndexBytes(index)
}

func LabelFromLabelSizesKey(key []byte) (uint64, error) {
	ctx := &storage.DataContext{}
	indexBytes, err := ctx.IndexFromKey(key)
	if err != nil {
		return 0, err
	}
	return binary.BigEndian.Uint64(indexBytes[9:17]), nil
}

// NewLabelSurfaceIndex returns an identifier for a given label's surface.
func NewLabelSurfaceIndex(label uint64) []byte {
	index := make([]byte, 1+8)
	index[0] = byte(KeyLabelSurface)
	binary.BigEndian.PutUint64(index[1:9], label)
	return dvid.IndexBytes(index)
}
