# Example simple configuration for DVID with single database backend.
# See config-multidb.toml for full range of configurations including
# email notifications, authentication, and backend assignments.

# NOTE: These example paths use /tmp to allow this configuration to
#       run on your machine out-of-the-box, for demonstration purposes.
#       For a real setup, change these paths to something permanent!

[server]
# host = "mygreatserver.test.com"  # Lets you specify a user-friendly alias for help messages.
httpAddress = ":8000"
rpcAddress = ":8001"
webClient = "./http/dvid-web-console"
webDefaultFile = "index.html" # contents of this file will be returned for any bad file path; required by dvid-console 3.0+

[logging]
logfile = "/tmp/dvid.log"
max_log_size = 500 # MB
max_log_age = 30   # days

# If no backend is specified, DVID will return an error unless there is only
# one store, which will automatically be backend.default.
# See config-full.toml for example of [backend] use.
# However, use of a labelmap instance requires at least a filelog store and
# specification of a log, so a backend is required for servers with labelmap
# instances.

# NOTE: If you plan to use labelmap type, you MUST specify a log and therefore
#       need to specify both "backend" and "store" sections.
#       See config-full.toml.

[backend]
    [backend.default]
    store = "instancedata"
    log = "mutationlog"  # required if you have a labelmap instance.

# List the different storage systems available for metadata, data instances, etc.
# Any nickname can be used for a store.  In this case, it's "raid6" to reflect
# that the directory is on a RAID-6 drive system.  Note that all store properties
# like "engine" and "path" should be lower-case by convention.

[store]
    [store.instancedata]
    engine = "badger"
    path = "/tmp/badgerdb"

    [store.mutationlog]
    engine = "filelog"
    path = "/tmp/mutationlog"  # directory that holds mutation log per instance-UUID.
